In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_hdf('data1.h5','df_sub')

In [26]:
def remove_duplicated(df):
    return_df = df.copy()
    is_duplicated = return_df.duplicated('moteid')
    return_df = return_df[~is_duplicated]
    return return_df
# remove_duplicated(df_epoch)

In [3]:
df2 = df[df['epoch'] == 2]

In [4]:
moteid_dict = {}

In [5]:
moteid_list = pd.unique(df['moteid'])

In [6]:
moteid_list

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 58])

In [7]:
for id in moteid_list:
    num = len(df[df['moteid'] == id])
    moteid_dict[id] = num

In [8]:
moteid_dict

{1: 43047,
 2: 46915,
 3: 46633,
 4: 43793,
 6: 35666,
 7: 55354,
 8: 15809,
 9: 45204,
 10: 47155,
 11: 41833,
 12: 19016,
 13: 27013,
 14: 26667,
 15: 2038,
 16: 32998,
 17: 33779,
 18: 33433,
 19: 39455,
 20: 28832,
 21: 58521,
 22: 60164,
 23: 62409,
 24: 57352,
 25: 53162,
 26: 61513,
 27: 37627,
 29: 64384,
 30: 38343,
 31: 65689,
 32: 43092,
 33: 35749,
 34: 48764,
 35: 51338,
 36: 56357,
 37: 47915,
 38: 49155,
 39: 32736,
 40: 46621,
 41: 40836,
 42: 44860,
 43: 38656,
 44: 47681,
 45: 53245,
 46: 52988,
 47: 56858,
 48: 58215,
 49: 34811,
 50: 15737,
 51: 42259,
 52: 34067,
 53: 25622,
 54: 28718,
 55: 2850,
 56: 2372,
 58: 4497}

In [9]:
moteid_dict_sorted = sorted(moteid_dict.items(),key=lambda kv:(kv[1],kv[0]),reverse=True)
moteid_dict_sorted = np.array(moteid_dict_sorted)

In [10]:
moteid_dict_sorted

array([[   31, 65689],
       [   29, 64384],
       [   23, 62409],
       [   26, 61513],
       [   22, 60164],
       [   21, 58521],
       [   48, 58215],
       [   24, 57352],
       [   47, 56858],
       [   36, 56357],
       [    7, 55354],
       [   45, 53245],
       [   25, 53162],
       [   46, 52988],
       [   35, 51338],
       [   38, 49155],
       [   34, 48764],
       [   37, 47915],
       [   44, 47681],
       [   10, 47155],
       [    2, 46915],
       [    3, 46633],
       [   40, 46621],
       [    9, 45204],
       [   42, 44860],
       [    4, 43793],
       [   32, 43092],
       [    1, 43047],
       [   51, 42259],
       [   11, 41833],
       [   41, 40836],
       [   19, 39455],
       [   43, 38656],
       [   30, 38343],
       [   27, 37627],
       [   33, 35749],
       [    6, 35666],
       [   49, 34811],
       [   52, 34067],
       [   17, 33779],
       [   18, 33433],
       [   16, 32998],
       [   39, 32736],
       [   

In [32]:
moteid_list_new = moteid_dict_sorted[:33].T[0]
print(moteid_list_new)

[31 29 23 26 22 21 48 24 47 36  7 45 25 46 35 38 34 37 44 10  2  3 40  9
 42  4 32  1 51 11 41 19 43]


In [41]:
epoch_id_list = pd.unique(df['epoch'])

In [42]:
df[df['epoch'] == epoch_id_list[2]]

datetime  epoch  moteid  temperature  humidity  \
2       2004-02-28 01:03:16.333930     11       1      19.3024  38.46290   
89971   2004-03-30 14:46:16.080796     11       3     122.1530  -3.91901   
513515  2004-02-28 06:26:46.945042     11      15      15.6568  44.31620   
515849  2004-03-17 15:25:59.203978     11      16     122.1530  -3.91901   
550483  2004-02-28 01:10:46.180433     11      17      18.4792  39.95910   
550484  2004-03-20 02:49:50.330131     11      17     122.1530  -3.91901   
550485  2004-03-20 03:03:50.291015     11      17     122.1530  -3.91901   
619551  2004-02-28 01:03:16.699203     11      19      19.0672  38.56520   
687838  2004-02-28 01:03:16.922930     11      21      19.3710  37.67650   
979510  2004-02-28 01:03:16.133126     11      26      18.6164  41.47800   
1125095 2004-02-28 01:03:16.399785     11      29      19.0280  39.55210   
1375151 2004-02-28 01:03:16.886569     11      34      18.5576  41.10780   
1475272 2004-02-28 01:03:16.179903     11      36      18.9496  41.14140   
1662846 2004-02-28 01:03:16.981838     11      40      18.8810  39.14430   
2267915 2004-03-31 04:19:29.570624     11      54     122.1530  23.52610   
2306147 2004-04-05 10:39:03.058457     11      56      24.2416  33.70000   
2308660 2004-04-01 14:24:48.943245     11      58      27.7010  22.09850   

              light  voltage  
2          45.08000  2.68742  
89971     397.44000  2.13640  
513515      5.52000  2.42416  
515849   1847.36000  2.25825  
550483     32.20000  2.57108  
550484    121.44000  2.08393  
550485    121.44000  2.07664  
619551     71.76000  2.68742  
687838    114.08000  2.69964  
979510    121.44000  2.68742  
1125095   180.32000  2.67532  
1375151    60.72000  2.67532  
1475272    79.12000  2.67532  
1662846   172.96000  2.68742  
2267915     0.46000  1.99973  
2306147     0.02011  2.82819  
2308660   143.52000  2.88311

In [14]:
epoch_length_dict = {}
for epoch in epoch_id_list:
    epoch_length_dict[epoch] = len(df[df['epoch'] == epoch])

In [15]:
dict_values = np.fromiter(epoch_length_dict.values(),dtype=int)

In [17]:
df_epoch = df[df['epoch'] == epoch_list[2]]

In [29]:
df_epoch

datetime  epoch  moteid  temperature  humidity  \
2       2004-02-28 01:03:16.333930     11       1      19.3024  38.46290   
89971   2004-03-30 14:46:16.080796     11       3     122.1530  -3.91901   
513515  2004-02-28 06:26:46.945042     11      15      15.6568  44.31620   
515849  2004-03-17 15:25:59.203978     11      16     122.1530  -3.91901   
550483  2004-02-28 01:10:46.180433     11      17      18.4792  39.95910   
550484  2004-03-20 02:49:50.330131     11      17     122.1530  -3.91901   
550485  2004-03-20 03:03:50.291015     11      17     122.1530  -3.91901   
619551  2004-02-28 01:03:16.699203     11      19      19.0672  38.56520   
687838  2004-02-28 01:03:16.922930     11      21      19.3710  37.67650   
979510  2004-02-28 01:03:16.133126     11      26      18.6164  41.47800   
1125095 2004-02-28 01:03:16.399785     11      29      19.0280  39.55210   
1375151 2004-02-28 01:03:16.886569     11      34      18.5576  41.10780   
1475272 2004-02-28 01:03:16.179903     11      36      18.9496  41.14140   
1662846 2004-02-28 01:03:16.981838     11      40      18.8810  39.14430   
2267915 2004-03-31 04:19:29.570624     11      54     122.1530  23.52610   
2306147 2004-04-05 10:39:03.058457     11      56      24.2416  33.70000   
2308660 2004-04-01 14:24:48.943245     11      58      27.7010  22.09850   

              light  voltage  
2          45.08000  2.68742  
89971     397.44000  2.13640  
513515      5.52000  2.42416  
515849   1847.36000  2.25825  
550483     32.20000  2.57108  
550484    121.44000  2.08393  
550485    121.44000  2.07664  
619551     71.76000  2.68742  
687838    114.08000  2.69964  
979510    121.44000  2.68742  
1125095   180.32000  2.67532  
1375151    60.72000  2.67532  
1475272    79.12000  2.67532  
1662846   172.96000  2.68742  
2267915     0.46000  1.99973  
2306147     0.02011  2.82819  
2308660   143.52000  2.88311

In [39]:
moteid_list_new_sorted = sorted(moteid_list_new)
print(moteid_list_new_sorted)

[1, 2, 3, 4, 7, 9, 10, 11, 19, 21, 22, 23, 24, 25, 26, 29, 31, 32, 34, 35, 36, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 48, 51]


In [43]:
df_list = []
for epoch in epoch_id_list:
    sub_df = df[df['epoch'] == epoch]
    sub_df = remove_duplicated(sub_df)
    df_list.append(sub_df)

In [44]:
len(df_list)

65536

In [89]:
diff_list = []
len_diff_list = []
for iter_df in df_list:
    id_list = sorted(iter_df['moteid'].values)
    diff = np.setdiff1d(moteid_list_new_sorted,id_list)
    diff_list.append(diff)
    len_diff_list.append(len(diff))

In [84]:
len_diff_array = np.array(len_diff_list)


In [93]:
np.where(len_diff_array == 0)

(array([16304, 16699, 16762, 19378, 19381, 19391, 19400, 19401, 19403,
        19496, 19510, 19513, 19530, 19552, 19681, 19723, 19759, 19795,
        19829, 19858, 19894, 19950, 19952, 19968, 19981, 20004, 20005,
        20041, 20101, 20134, 20169, 20218, 20228, 20232, 20290, 20335,
        20360, 20436, 20537, 20567, 20570, 20579, 20587, 20602, 20609,
        20650, 20684, 20701, 20708, 20711, 20738, 20796, 20801, 20806,
        20810, 20813, 20858, 20871, 20878, 20906, 20911, 20945, 20953,
        21012, 21015, 21016, 21047, 21055, 21058, 21059, 21067, 21085,
        21111, 21119, 21125, 21130, 21149, 21154, 21157, 21160, 21161,
        21167, 21175, 21260, 21268, 21275, 21530, 21673, 21708, 21713,
        21719, 21720, 21722, 21724, 21726, 21738, 21740, 21770, 21801,
        21802, 21817, 21828, 21862, 21889, 21907, 21920, 21952, 21954,
        21981, 21982, 21989, 21991, 22019, 24079, 24166, 24175, 24204,
        24323, 24416, 24462, 24620, 24679, 24696, 24737, 24755, 24829,
      

In [92]:
df_list[np.where(len_diff_array == 0)[0][0]]

datetime  epoch  moteid  temperature  humidity  \
16306   2004-03-07 20:56:11.457776  25436       1      23.4870   39.1783   
55774   2004-03-07 20:56:13.423919  25436       2      23.7222   39.8913   
106595  2004-03-07 20:56:11.777773  25436       3      23.5164   39.4842   
151467  2004-03-07 20:56:15.833759  25436       4      23.5948   40.0268   
237292  2004-03-07 20:56:09.890248  25436       7      23.2322   39.8235   
284058  2004-03-07 20:56:16.764334  25436       8      22.8108   40.3990   
306443  2004-03-07 20:56:06.543326  25436       9      22.7912   41.9818   
354790  2004-03-07 20:56:08.866191  25436      10      22.7030   42.1160   
401998  2004-03-07 20:56:12.363688  25436      11      21.6838   45.1103   
435656  2004-03-07 20:56:15.220686  25436      12      20.7332   46.8851   
461011  2004-03-07 20:56:20.520795  25436      13      21.4388   46.0655   
529875  2004-03-07 20:55:43.562878  25436      16      21.7818   45.2423   
566395  2004-03-07 20:56:05.466156  25436      17      22.9284   41.0067   
604541  2004-03-07 20:56:19.322975  25436      18      24.4572   40.3652   
633323  2004-03-07 20:56:04.797574  25436      19      23.4674   39.9591   
680658  2004-03-07 20:56:09.997755  25436      20      23.1342   41.7805   
709588  2004-03-07 20:56:08.357652  25436      21      23.8300   38.7698   
768965  2004-03-07 20:56:06.643337  25436      22      23.5752   39.2803   
826420  2004-03-07 20:56:13.157824  25436      23      24.1534   38.2922   
886714  2004-03-07 20:56:14.024990  25436      24      23.7124   39.0082   
943562  2004-03-07 20:56:11.429426  25436      25      23.4086   39.5521   
1005785 2004-03-07 20:56:05.665097  25436      26      23.2616   40.9055   
1050310 2004-03-07 20:56:03.563561  25436      27      23.9966   38.7698   
1139345 2004-03-07 20:56:05.026740  25436      29      23.7614   39.0082   
1252099 2004-03-07 20:56:12.172917  25436      31      23.4380   39.8913   
1306597 2004-03-07 20:56:03.697541  25436      32      23.2224   40.0607   
1348407 2004-03-07 20:56:04.363506  25436      33      23.7908   38.5311   
1387193 2004-03-07 20:56:08.149577  25436      34      23.6046   39.6878   
1442133 2004-03-07 20:56:15.720126  25436      35      24.2220   40.2638   
1494317 2004-03-07 20:56:09.945124  25436      36      23.8888   40.9392   
1551104 2004-03-07 20:56:14.097848  25436      37      24.3690   41.0067   
1599025 2004-03-07 20:56:18.080681  25436      38      23.9770   38.3946   
1640637 2004-03-07 20:56:05.862205  25436      39      24.5160   38.9061   
1678931 2004-03-07 20:56:12.927822  25436      40      24.3200   38.2580   
1723802 2004-03-07 20:56:09.821106  25436      41      24.0358   38.4287   
1766397 2004-03-07 20:56:06.643162  25436      42      23.7908   39.1783   
1809768 2004-03-07 20:56:16.822300  25436      43      24.1828   37.8477   
1854452 2004-03-07 20:56:05.117550  25436      44      24.3494   37.9845   
1906580 2004-03-07 20:56:04.263751  25436      45      24.5356   37.0246   
1959346 2004-03-07 20:56:17.758027  25436      46      24.7610   37.5737   
2013259 2004-03-07 20:56:09.083027  25436      47      24.7316   38.1213   
2070953 2004-03-07 20:56:08.177645  25436      48      24.5356   38.3263   
2121185 2004-03-07 20:56:10.732821  25436      49      24.2024   37.9161   
2160041 2004-03-07 20:56:03.662187  25436      50      23.9476   39.8913   
2179023 2004-03-07 20:56:11.308930  25436      51      24.6042   38.3263   
2217723 2004-03-07 20:56:07.364091  25436      52      24.4964   38.8039   
2250337 2004-03-07 20:56:10.657726  25436      53      23.5752   41.1751   

          light  voltage  
16306     46.92  2.63964  
55774    128.80  2.61639  
106595    50.60  2.65143  
151467   101.20  2.59354  
237292   101.20  2.62796  
284058   114.08  2.62796  
306443    97.52  2.68742  
354790    60.72  2.60491  
401998     2.30  2.57108  
435656     0.92  2.59354  
461011     1.84  2.59354  
529875     1.38  2.57108  
566395     7.36  2.52732  

In [ ]:
df_list[16698]